POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json 
Authorization: 123456

{
    "user_id":"1",
    "user_message": "Olá, quel é o seu nome?"
}

###
POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json 
Authorization: 123456

{   "chat_id": "7d36175f-3ac7-4cc0-bb16-4ab1a6b6829f",
    "user_id":"1",
    "user_message": "O que é arquitetura de software"
}

###
POST http://localhost:8081/chat HTTP/1.1
Content-Type: application/json 
Authorization: 123456

{   "chat_id": "479ab854-e486-4bda-990c-4e1577dab1bc",
    "user_id":"1",
    "user_message": "Quando é o dia do ferroviário?"
}